# irc robot setting file

[irc]
server ="irc.org:6667"
password = ""
nick = "robot2"
channel = "#test"
mesi = true
logsize = 32

[log]
dir = "log"

[webs]
host = "0.0.0.0:9619"
username = "mesi"
password = "mesi"
# set pkcs12 file, if https connected else ""
pem = ""
