# irc robot setting file

[irc]
server ="irc.org:6667"
password = ""
nick = "robot2_v3"
channel = "#test"

[log]
dir = "log"

[webs]
host = "0.0.0.0:9619"
username = "mesi"
password = "mesi"
pem = ""
