-- Your SQL goes here

CREATE TABLE party (
    id INTEGER NOT NULL PRIMARY KEY,
    title VARCHAR NOT NULL,
    open_time TIMESTAMP,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    valid BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE member (
    id INTEGER NOT NULL PRIMARY KEY,
    name VARCHAR NOT NULL,
    pid INTEGER NOT NULL,
    create_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);